### ISSUE TITLE
Not working on Ubuntu 22.04 + ROS 2 Humble 

### ISSUE THREAD

**Issue by JLBicho** [bitmeal/cap-grant-ld#1]
Hello, 

I'm currently working with the following setup:

- Ubuntu 22.04
- ROS 2 Humble
- [SOEM](https://github.com/OpenEtherCATsociety/SOEM)

With root user the EtherCAT interface is working properly. 
I've installed `cap_grand_ld` with `colcon` and used `prefix = 'ros2 run cap_grant_ld cap_grant_ld'` in the `launch` file. The launch works correctly as the node starts but when it tries to connect to EtherCAT I get an error saying that the interface is not available. It's the same interface as with root user.

Could I be missing something regarding the installation for ROS packages?

Thanks in advance!

**Comment by bitmeal** [comment]
> *This is a follow up to shadow-robot/ethercat_grant#10, linking for reference and notification in the the respective issue in original repo.*

Now to address your issue:
Did your set the necessary capabilities on the grant executable `cap_grant_ld`? See the example in the README https://github.com/bitmeal/cap-grant-ld#usage For EtherCAT you will need at least `cap_net_raw` capability, and if you need realtime operations, likely `cap_sys_nice` as well.

Find where the executable resides and from that directory call:
```bash
sudo setcap cap_net_raw,cap_sys_nice+ep ./cap_grant_ld
```

**Comment by bitmeal** [comment]
@JLBicho any news on the matter? has the issue been resolved?

**Comment by JLBicho** [comment]
Hello!
Sorry for the delay, I didn't have access to the system until today.

I had not granted the executable permissions because I jumped straight to the ROS section, hehe... My bad.

Now it works perfectly! Thank you very much! 

From my side we can close this issue.
